spring.application.name=EnlazadosTW

# ====================
# Base de datos
# ====================
spring.datasource.url=jdbc:postgresql://localhost:5432/enlazadosbd
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ====================
# JWT Configuration
# ====================
app.jwt.secret=mySecretKeyForJWTTokenGenerationPleaseChangeInProduction1234567890
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

# ====================
# Email / Gmail SMTP
# ====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jonaspacheco268@gmail.com
spring.mail.password=tfrn fatd vshc qcwf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.email.from=jonaspacheco268@gmail.com
app.email.verification-expiration-minutes=1440
app.email.password-reset-expiration-minutes=30
app.frontend.verify-email-url= http://localhost:8100/verify-email
app.frontend.reset-password-url= http://localhost:8100/reset-password
app.frontend.therapeutic-team-invitation-url=http://localhost:8100/therapeutic-team-invitation

# ====================
# Server Configuration
# ====================
server.port=8080

# ====================
# Swagger / OpenAPI Configuration
# ====================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.filter=true
